# Site settings
title_text: My Website
full_name: 
email: johncorderox@gmail.com

location: Tokyo, Japan
bio_text: Coffee Lover, Food Blogger, Graphic Artist
bio_description: 

linkedin: 
github: 
twitter:

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-sitemap, jekyll-seo-tag]


